
FROM node:20.13.1-alpine
# Set the working directory.
WORKDIR /react/app

RUN npm install -g react-scripts


RUN chown -Rh node:node /react/app

# Copy the package.json file.
COPY ./web/package*.json .
COPY ./web/ .

USER node



# Expose the port.
EXPOSE 3000

# Run the application.
CMD [ "sh", "-c", "npm install && npm start" ]