FROM node:20.13.1-alpine
# Set the working directory.
WORKDIR /react/app

# Copy the package.json file.
COPY package*.json .

COPY . .

# Install application dependencies.
RUN npm install


# Expose the port.
EXPOSE 3000

# Run the application.
CMD ["npm","run", "start"]